apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tenant-a-ml-inference
  namespace: tenant-a
  labels:
    app: ml-inference
    tenant: tenant-a
spec:
  selector:
    matchLabels:
      app: ml-inference
      tenant: tenant-a
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tenant-b-ml-inference
  namespace: tenant-b
  labels:
    app: ml-inference
    tenant: tenant-b
spec:
  selector:
    matchLabels:
      app: ml-inference
      tenant: tenant-b
  endpoints:
    - port: http
      path: /metrics
      interval: 30s

