apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant-b-ml-inference-role
  namespace: tenant-b
  labels:
    app: ml-inference
    tenant: tenant-b
rules:
  # Allow reading config maps and secrets
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
  # Allow reading pods (for self-discovery)
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

